spring.application.name=aldrop

server.port=4000

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD:}

aldrop.platform-admin.username=${PLATFORM_ADMIN_USERNAME}
aldrop.platform-admin.password=${PLATFORM_ADMIN_PASSWORD}
